### ISSUE TITLE
DataFrance Store does not update on cell edit

### ISSUE THREAD

**Issue by dkrasner** [darth-cheney/ap-sheet#16]
### Main Issue ###

Cell editing does not update the sheet.dataFrame.store. For example:
![image](https://user-images.githubusercontent.com/1154326/171170118-eede8f38-665b-4bdc-ab7a-500cc250e617.png)

the 3 console logs on the store you see are before I hit clear, after, and after I entered the "AAA" value into cell 0,0

**Comment by darth-cheney** [comment]
@dkrasner I have just pushed a fix for this straight to master. Let me know if there's any trouble. Otherwise feel free to close.

**Comment by dkrasner** [comment]
@darth-cheney cool closing tu
