### ISSUE TITLE
Frame size is wrong

### ISSUE THREAD

**Issue by dkrasner** [darth-cheney/ap-sheet#29]
`Frame(0, 100).size = Point(100, 100)` where its actual size is 101x101

This happens due to the classic errors that arise when thinking about 0 indexed  vs 1 indexed arrays

I think this should be handled together with #22

**Comment by dkrasner** [comment]
There are other lurking issues and this is going to screw many things up in the future:

for example:

```
const array1 = [
    [1, 2, 3],
    [4, 5, 6]
]
const s = new Sheet([0, 0], [0, 0)])
s.dataFrame.loadFromArray(array1);
s.size // (2, 1) as expected
s.corner.x // 2 as expected
s.corner.y  // 1 as expected

const array2 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
s.dataFrame.loadFromArray(array1);

s.size // (2, 3) wtf!
s.corner.x // 2 as expected
s.corner.y  // 3 wtf!
```

the point (2,3) is not even in the sheet, and it's corner should be (2x2) - this. is pretty messed up

**Comment by dkrasner** [comment]
ap-sheet

**Comment by darth-cheney** [comment]
ap-sheets -- meaning the actual element -- do not have a `size` method, so I'm not sure what the example code is trying to do. Do you mean to get the `size` of the DataFrame?

**Comment by dkrasner** [comment]
s = ap-sheet

everything above refers to the data frame ie s.dataFrame (there is a typo there, should be s.dataFrame for everything)
