### ISSUE TITLE
'editing' CSS class not removed from cell

### ISSUE THREAD

**Issue by dkrasner** [darth-cheney/ap-sheet#4]
### Main Points ###

Cursor out of an editing cell (without pressing `enter`) and the `editing` css class does not get remove leaving the following styling hanging out: 

![image](https://user-images.githubusercontent.com/1154326/165945224-4f430aef-edad-4b3c-88e3-0b1782ece4d6.png)

**Comment by radna0** [comment]
Can you explain it in more details?
